Repository strongnidhi/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#2 Create n_Queens _Problem.java
  Java/n_Queens _Problem.java
Labels: hacktoberfest, accepted

#3 graph algorithms
  C++/floyd warshell.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#5 Create n_Queens _Problem.java
  Java/n_Queens _Problem.java
Labels: hacktoberfest, accepted, hacktoberfest-accepted

#4 merging sort created
  Python/merge_sort.py
Labels: hacktoberfest, hacktoberfest-accepted

#6 Leetcode problem solution with explanation.
  C++/array_is_sorted_&_rotated.cpp
  C++/elemet_present_in_array_or_not.cpp
  C++/reverse_array.cpp
  C++/rotate_array_by_one.cpp
  C++/second_largest_element_without_using_sorting.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#9 Create lottery.java
  Java/lottery.java
Labels: hacktoberfest, hacktoberfest-accepted

#10 Create student.java
  Java/student.java
Labels: hacktoberfest, hacktoberfest-accepted

#11 Create heaps.java
  Java/heaps.java
Labels: hacktoberfest, hacktoberfest-accepted
